name: Publish Environment on qBraid

on:
  workflow_dispatch:
    inputs:
      environment-file:
        description: "Path to the yaml config file"
        required: true
        type: string 
        default: '.qbraid.yaml'
      wait-for-completion:
        description: "Wait for the environment to be published"
        required: true
        type: boolean
        default: false

jobs:
  publish_env:
    runs-on: ubuntu-latest 
    steps:
      - name: Publish Environment
        uses: TheGupta2012/test-github-action@v2.6
        with:
          environment-file: ${{ github.event.inputs.environment-file }}
          wait-for-completion: ${{ github.event.inputs.wait-for-completion }}
          api-key: ${{ secrets.QBRAID_API_KEY }}